const express=require("express")
const server=express()
//const morgan=require("morgan")
const logger=require("./middleware/logger")
const bp=require("body-parser")
const cors=require("cors")
server.use(bp.json())
//server.use(morgan('tiny'))
server.use(logger)
server.use(cors())
const createContact=require("./routes/createContact")
const viewAll=require("./routes/viewContact")
const searchFname=require("./routes/searchContact")
const searchID=require("./routes/searchContactByID")
const updateContact=require("./routes/updateContact")
const updateByID=require("./routes/updateByID")
const deleteContact=require("./routes/deleteContact")
server.use("/",createContact)
server.use("/",viewAll)
server.use("/",searchFname)
server.use("/",searchID)
server.use("/",updateContact)
server.use("/",updateByID)
server.use("/",deleteContact)
server.listen(process.env.PORT||3001,()=>console.log("server has started at port no : 3001"))
